/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobportal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author super
 */
public class Forms extends javax.swing.JFrame {

    Connection conn=null;
    /**
     * Creates new form Forms
     */
    public Forms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tyg = new javax.swing.JTextField();
        edug = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        expg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        educational = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ex = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setForeground(new java.awt.Color(0, 51, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JOB GIVER FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 330, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Education Level Needed:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 230, 200, 40);

        addg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addgActionPerformed(evt);
            }
        });
        jPanel1.add(addg);
        addg.setBounds(50, 380, 330, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EXPERIENCE:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 450, 120, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TYPE OF JOB:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 110, 200, 40);
        jPanel1.add(tyg);
        tyg.setBounds(50, 160, 330, 50);
        jPanel1.add(edug);
        edug.setBounds(50, 270, 330, 50);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 490, 130, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 330, 200, 40);
        jPanel1.add(expg);
        expg.setBounds(140, 460, 70, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 550);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("JOB SEEKER:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 30, 210, 50);

        jLabel7.setText("EDUCATIONAL LEVEL");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 210, 130, 40);
        getContentPane().add(educational);
        educational.setBounds(480, 250, 320, 50);

        jLabel8.setText("YOUR EXPERIENCE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 430, 120, 40);

        jLabel9.setText("TYPE OF JOB:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 120, 130, 40);
        getContentPane().add(address);
        address.setBounds(490, 370, 320, 50);
        getContentPane().add(type);
        type.setBounds(480, 160, 310, 50);

        jLabel10.setText("ADDRESS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 330, 130, 40);
        getContentPane().add(ex);
        ex.setBounds(510, 470, 90, 40);

        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 490, 110, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addgActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/job","root","");
            String sql="INSERT INTO JobGiver(TypeJob,EducationalLevel,Address,Experience) VALUES(?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,tyg.getText());
            pst.setString(2,edug.getText());
            pst.setString(3,addg.getText());
            pst.setString(4,expg.getText());
            pst.executeUpdate();
     
                  JOptionPane.showMessageDialog(null,"Submitted Sucessfuly");
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/job","root","");
            String sql="INSERT INTO JobGiver(TypeJob,EducationalLevel,Address,Experience) VALUES(?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,type.getText());
            pst.setString(2,educational.getText());
            pst.setString(3,address.getText());
            pst.setString(4,ex.getText());
            pst.executeUpdate();
     
                  JOptionPane.showMessageDialog(null,"Submitted Sucessfuly");
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addg;
    private javax.swing.JTextField address;
    private javax.swing.JTextField educational;
    private javax.swing.JTextField edug;
    private javax.swing.JTextField ex;
    private javax.swing.JTextField expg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tyg;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
